export const benefits = [
  {
    id: 1,
    title: "Generate engaging copy in seconds",
    description:
      "Quickly assemble professional copy with our library of customizable templates and components.",
    img: "/benefit2.jpg",
  },
  {
    id: 2,
    title: "Ready-Made Engagement",
    description:
      "Effortlessly create engaging content using our comprehensive collection of templates and components.",
    img: "/benefit1.jpg",
  },
  {
    id: 3,
    title: "Customize & Assemble",
    description:
      "Quickly assemble professional copy with our library of customizable templates and components.",
    img: "/benefit2.jpg",
  },
];


export const reviews = [
  {
    id: 1,
    content: "The tool was surprisingly easy to use and the AI generated copy that was far better than I could have come up with on my own. The templates were also a big help in streamlining my content creation process.",
    name: "Jordan Conor",
    role: "Founder, Fortura UI.",
    img: "/profile1.jpg",
  },
  {
    id: 2,
    content: "I was impressed by how well the AI understood my brand voice and tone.",
    name: "David Anslem.",
    role: "Founder, Fortura UI.",
    img: "/profile2.jpg",
  },
  {
    id: 3,
    content: "The AI really helped me overcome writer's block and come up with fresh ideas for my blog posts. I was able to quickly generate engaging content that my readers loved.",
    name: "Anthonia Danielson.",
    role: "Founder, Fortura UI.",
    img: "/profile3.jpg",
  },
  {
    id: 4,
    content: "The tool was surprisingly easy to use and the AI generated copy that was far better than I could have come up with on my own. The templates were also a big help in streamlining my content creation process.",
    name: "Jordan Conor",
    role: "Mary Cane.",
    img: "/profile4.jpg",
  },
  {
    id: 5,
    content: "I was skeptical at first, but the AI was able to create high-quality copy that sounded just like it came from a professional writer. The templates were easy to use and saved me a lot of time.",
    name: "Anthony Lee",
    role: "Founder, Fortura UI.",
    img: "/profile2.jpg",
  },
  {
    id: 6,
    content: "As someone who struggles with writing, I was amazed at how quickly and effectively the AI was able to generate high-quality content for me. It saved me a lot of time and stress, and allowed me to focus on other aspects of my business.",
    name: "Cynthia Morgan",
    role: "Founder, Fortura UI.",
    img: "/profile4.jpg",
  },
];

export const monthlyPrices = [
  {
    id: 1,
    type: "Beginner",
    words: 2000,
    price: 9,
    details: "Suitable for designers taking on 1 project per month."
  },
  {
    id: 2,
    type: "Starter",
    words: 10000,
    price: 19,
    details: "Suitable for designers taking on 1-3 projects per month."
  },
  {
    id: 3,
    type: "Pro",
    words: 50000,
    price: 59,
    details: "Suitable for designers taking on 3+ projects per month."
  },
]

export const yearlyPrices = [
  {
    id: 1,
    type: "Beginner",
    words: 2000,
    save: 18,
    price: 90,
    details: "Suitable for designers taking on 1 project per month."
  },
  {
    id: 2,
    type: "Starter",
    words: 10000,
    save: 38,
    price: 199,
    details: "Suitable for designers taking on 1-3 projects per month."
  },
  {
    id: 3,
    type: "Pro",
    words: 50000,
    save: 118,
    price: 599,
    details: "Suitable for designers taking on 3+ projects per month."
  },
]

export const faqs = [
  {
    id: 1,
    title: "How do I know the copy generated by the AI will be good?",
    description: "Our AI has been trained on a large corpus of human-written content, so it’s able to generate copy that sounds natural and engaging. Plus, you can customize the tone and style of the content to match your brand.",
  },
  {
    id: 2,
    title: "Can I use the tool to generate content in different languages?",
    description: " At this time, the tool can only generate content in English. However, we may add support for additional languages in the future.",
  },
  {
    id: 3,
    title: "What if I don’t like the copy generated by the AI?",
    description: "If you’re not happy with the content generated by the AI, you can always edit it to your liking or generate a new version with different inputs.",
  },
  {
    id: 4,
    title: "Can I use the tool to generate long-form content, like blog posts?",
    description: "While the tool is best suited for short-form content like social media posts and ads, you can also use it to generate the outline or rough draft of a blog post.",
  },
  {
    id: 5,
    title: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolores, ea.",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eaque tempore vel nostrum optio nobis ullam explicabo iure cumque! Impedit saepe vitae fugit, repellendus tenetur quia quo amet nisi dolorum deserunt. Lorem ipsum dolor sit amet consectetur adipisicing elit. Sapiente unde magni corrupti aliquid autem error recusandae earum cum, tempore iste.",
  },
  {
    id: 6,
    title: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolores, ea.",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eaque tempore vel nostrum optio nobis ullam explicabo iure cumque! Impedit saepe vitae fugit, repellendus tenetur quia quo amet nisi dolorum deserunt. Lorem ipsum dolor sit amet consectetur adipisicing elit. Sapiente unde magni corrupti aliquid autem error recusandae earum cum, tempore iste.",
  },
]